language: python
python:
  - "2.7"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
env:
  - DB=sqlite
# add db user
before_script:
  - psql -c "CREATE USER test_user WITH PASSWORD 'test_password';" -U postgres;
  - psql -c "ALTER USER test_user CREATEDB;" -U postgres;
# command to run tests
script: python lifelist/manage.py test
after_success:
  - coveralls
